@startuml
'https://plantuml.com/class-diagram'

abstract class Student_basis{
     -id: Integer
     -phone: String
     -telegram: String
     -email: String
     -git: String
--
     +{static}is_val_git?(String): Boolean
     +initialize(Hash)
     +contact?(): Boolean
     +validate(): Boolean
     +get_concats(): String
     .. getters..
     git(): String
     .. setters ..
     +git(): String
     +id():Integer
}

class Student extends Student_basis{
     -lastname: String
     -firstname: String
     -father_name: String
     +{static}from_json(String):Student
     +{static}is_val_name?(String): Boolean
     +{static}is_val_phone?(String): Boolean
     +{static}is_val_telegram?(String): Boolean
     +{static}is_val_email?(String): Boolean
     +initialize(Hash)
     +set_contacts(Hash)
     +to_s(): String
     +get_info(): String
     +to_json():String
     .. getters ..
     +phone(): String
     +telegram(): String
     +email(): String
     +last_name(): String
     +first_name(): String
     +father_name(): String
     .. setters ..
     +phone=(String)
     +telegram=(String)
     +email=(String)
     +last_name=(String)
     +first_name=(String)
     +father_name=(String)

}

class Student_short extends Student_basis{
     -lastname_and_initials: String
     -contact: Hash
     {static}from_student(Student): ShortStudent
     +initialize(Integer, String)
     +to_s(): String
     .. getters ..
     +lastname_and_initials(): String
     +contact(): Hash
     .. setters ..
     -lastname_and_initials=(String)
     -contact=(Hash)
}
@enduml
